/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package guardian.backend;

import java.util.Date;

import javax.swing.text.DateFormatter;

import java.util.ArrayList;

import guardian.backend.model.ArrayConverterFactory;

public class App {
    public static void main(String[] args) {
        ArrayList<Date> oldTestArrayList = new ArrayList<Date>();
        oldTestArrayList.add(new Date());
        oldTestArrayList.add(new Date());
        String json = new ArrayConverterFactory().dateArrayToJSON(oldTestArrayList);
        System.out.println(json);
        ArrayList<Date> newArrayList = new ArrayConverterFactory().jsonToDateArray(json);
        System.out.println(oldTestArrayList);
        System.out.println(newArrayList);
    }
}
